CREATE DATABASE GESTAO_TICKETS;

CREATE TABLE GESTAO_TICKETS.TICKETS (
  Id           BIGINT        NOT NULL AUTO_INCREMENT,
  Titulo         VARCHAR(1000)  NOT NULL,
  Descricao    VARCHAR(1000) NULL,
  DataAbertura TIMESTAMP  NOT NULL,
  CONSTRAINT PK_PRODUTO PRIMARY KEY (ID)
);

CREATE TABLE GESTAO_TICKETS.USUARIOS (
	ID BIGINT  NOT NULL AUTO_INCREMENT,
    CONSTRAINT PK_USUARIO PRIMARY KEY (ID),
    LOGIN VARCHAR(20) NOT NULL,
    NOME VARCHAR(50) NOT NULL,
    SENHA VARCHAR(10) NOT NULL,
    ATIVO VARCHAR(1)
);

INSERT INTO GESTAO_TICKETS.USUARIOS(LOGIN,NOME,SENHA,ATIVO) VALUES ("admin","Administrador","1234","S");